### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by chohner** [colibris-xyz/strapi-plugin-site-publisher#121]
👋🏼  any chance of a new release, which would include all the updated dependency specs?
Thanks :)

**Comment by chohner** [comment]
also, please consider merging https://github.com/colibris-xyz/strapi-plugin-site-publisher/pull/107 as axios <1.5.1 contains a moderate security vulnerability: https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

**Comment by tms0** [comment]
Hi @chohner,

I hope to release a new version this week.
