### ISSUE TITLE
Plugin is not visible in Sidebar

### ISSUE THREAD

**Issue by ohrie** [colibris-xyz/strapi-plugin-site-publisher#99]
Hello :)

I've just used the plugin, but cannot use it. The plugin just doesn't appear in die Sidebar in Strapi. Tested it with Strapi Version 4.10.5. The plugin does appear in the list of Plugins. The configuration is set in `plugins.js`.

Maybe the plugin does not get along with this new version of Strapi?

**Comment by zzev** [comment]
After installing the plugin you have to rebuild the app with either `npm run build` or `yarn run build` to see the plugin in the sidebar.
